# Gradle Project settings
projectName = app.settings
version = 1.0.0-SNAPSHOT

# XP App values
appDisplayName = App Settings
appName = com.enonic.app.settings
vendorName = Enonic AS
vendorUrl = https://enonic.com
xpVersion = 8.1.0-SNAPSHOT

# Settings for publishing to a Maven repo
group = com.enonic.xp
